export const blockNode = {
  type: "BlockStatement",
  body: [
    {
      type: "VariableDeclaration",
      kind: "const",
      declarations: [
        {
          type: "VariableDeclarator",
          id: {
            type: "ObjectPattern",
            properties: [
              {
                type: "ObjectProperty",
                key: {
                  type: "Identifier",
                  name: "className",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                value: {
                  type: "Identifier",
                  name: "className",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                computed: false,
                shorthand: true,
                decorators: null,
                leadingComments: undefined,
                innerComments: undefined,
                trailingComments: undefined,
              },
              {
                type: "ObjectProperty",
                key: {
                  type: "Identifier",
                  name: "variant",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                value: {
                  type: "Identifier",
                  name: "variant",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                computed: false,
                shorthand: true,
                decorators: null,
                leadingComments: undefined,
                innerComments: undefined,
                trailingComments: undefined,
              },
              {
                type: "ObjectProperty",
                key: {
                  type: "Identifier",
                  name: "size",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                value: {
                  type: "Identifier",
                  name: "size",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                computed: false,
                shorthand: true,
                decorators: null,
                leadingComments: undefined,
                innerComments: undefined,
                trailingComments: undefined,
              },
              {
                type: "RestElement",
                argument: {
                  type: "Identifier",
                  name: "t3",
                  leadingComments: undefined,
                  innerComments: undefined,
                  trailingComments: undefined,
                },
                leadingComments: undefined,
                innerComments: undefined,
                trailingComments: undefined,
              },
            ],
            leadingComments: undefined,
            innerComments: undefined,
            trailingComments: undefined,
          },
          init: {
            type: "Identifier",
            name: "t0",
            loc: {
              start: {
                line: 95,
                column: 16,
                index: 3349,
              },
              end: {
                line: 95,
                column: 67,
                index: 3400,
              },
              filename: undefined,
              identifierName: undefined,
            },
            leadingComments: undefined,
            innerComments: undefined,
            trailingComments: undefined,
          },
          leadingComments: undefined,
          innerComments: undefined,
          trailingComments: undefined,
        },
      ],
      loc: {
        start: {
          line: 95,
          column: 16,
          index: 3349,
        },
        end: {
          line: 95,
          column: 67,
          index: 3400,
        },
        filename: undefined,
        identifierName: undefined,
      },
      leadingComments: undefined,
      innerComments: undefined,
      trailingComments: undefined,
    },
    {
      type: "ExpressionStatement",
      expression: {
        type: "AssignmentExpression",
        operator: "=",
        left: {
          type: "Identifier",
          name: "props",
          leadingComments: undefined,
          innerComments: undefined,
          trailingComments: undefined,
        },
        right: {
          type: "Identifier",
          name: "t3",
          loc: Symbol(),
          leadingComments: undefined,
          innerComments: undefined,
          trailingComments: undefined,
        },
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined,
      },
      loc: {
        start: {
          line: 95,
          column: 16,
          index: 3349,
        },
        end: {
          line: 95,
          column: 67,
          index: 3400,
        },
        filename: undefined,
        identifierName: undefined,
      },
      leadingComments: undefined,
      innerComments: undefined,
      trailingComments: undefined,
    },
    // ...other declarations
  ],
  directives: [],
  leadingComments: undefined,
  innerComments: undefined,
  trailingComments: undefined,
};
